export const mockMeetings = [
  {
    id: 1,
    emoji: '🎵',
    theme: '음악 취향',
    title: '플리 공유 밥한끼',
    description: '요즘 꽂혀있는 노래 얘기하다 보면 금방 친해져요',
    status: 'recruiting',
    seats: { total: 4, remaining: 2 },
    time: '12:30 PM',
    relatedTopics: ['interest', 'leisure', 'free'],
    restaurant: {
      name: '동명식탁',
      address: '광주 동구 동명동 177-3',
      distance: '조선대 정문에서 도보 7분',
      category: '한식 정식',
      mapUrl: 'https://map.kakao.com/link/search/동명식탁',
      caution: '노쇼 시 환불 불가',
    },
    tags: ['음악감상', '요즘 관심사'],
    accentColor: '#7B2D8B',
    bgColor: '#F3E8FF',
  },
  {
    id: 2,
    emoji: '💻',
    theme: '사이드프로젝트',
    title: '요즘 뭐 만들어요?',
    description: '앱이든 영상이든 뭔가 만드는 사람들끼리 밥',
    status: 'closing',
    seats: { total: 4, remaining: 1 },
    time: '12:00 PM',
    relatedTopics: ['interest', 'career', 'free'],
    restaurant: {
      name: '카페 동명',
      address: '광주 동구 동명동 184-1',
      distance: '조선대 정문에서 도보 5분',
      category: '브런치 카페',
      mapUrl: 'https://map.kakao.com/link/search/카페동명+광주+동명동',
      caution: '노쇼 시 환불 불가',
    },
    tags: ['게임', '요즘 관심사'],
    accentColor: '#1565C0',
    bgColor: '#E3F2FD',
  },
  {
    id: 3,
    emoji: '🌏',
    theme: '여행 계획',
    title: '다음 여행지 같이 정해요',
    description: '혼자 고민하던 여행 계획, 같이 얘기해봐요',
    status: 'recruiting',
    seats: { total: 4, remaining: 3 },
    time: '12:30 PM',
    relatedTopics: ['leisure', 'free'],
    restaurant: {
      name: '북카페 서재',
      address: '광주 동구 동명동 201-5',
      distance: '조선대 쪽문에서 도보 4분',
      category: '북카페',
      mapUrl: 'https://map.kakao.com/link/search/북카페서재+광주+동명동',
      caution: '노쇼 시 환불 불가',
    },
    tags: ['여행', '맛집'],
    accentColor: '#00897B',
    bgColor: '#E0F2F1',
  },
  {
    id: 4,
    emoji: '🎬',
    theme: '영화·드라마',
    title: '요즘 뭐 봐요?',
    description: '넷플릭스 추천이 필요한 사람, 여기 모여요',
    status: 'recruiting',
    seats: { total: 4, remaining: 2 },
    time: '1:00 PM',
    relatedTopics: ['leisure', 'interest', 'free'],
    restaurant: {
      name: '아뜰리에 카페',
      address: '광주 동구 동명동 165-2',
      distance: '조선대 정문에서 도보 9분',
      category: '아트 카페',
      mapUrl: 'https://map.kakao.com/link/search/아뜰리에카페+광주+동명동',
      caution: '노쇼 시 환불 불가',
    },
    tags: ['영화', '예술'],
    accentColor: '#C62828',
    bgColor: '#FFEBEE',
  },
  {
    id: 5,
    emoji: '💼',
    theme: '취업·이직',
    title: '커리어 고민 털어놓기',
    description: '취업·이직 고민 있는 사람들끼리 솔직하게',
    status: 'recruiting',
    seats: { total: 4, remaining: 2 },
    time: '12:00 PM',
    relatedTopics: ['career', 'free'],
    restaurant: {
      name: '이웃집 커피',
      address: '광주 동구 동명동 193-8',
      distance: '조선대 정문에서 도보 6분',
      category: '스페셜티 카페',
      mapUrl: 'https://map.kakao.com/link/search/이웃집커피+광주+동명동',
      caution: '노쇼 시 환불 불가',
    },
    tags: ['취업·이직', '네트워킹'],
    accentColor: '#E8521A',
    bgColor: '#FFF1EC',
  },
  {
    id: 6,
    emoji: '📷',
    theme: '사진·필름',
    title: '필카 들고 밥 먹기',
    description: '골목 구경하고 필름 한 롤 찍고 밥 먹어요',
    status: 'matched',
    seats: { total: 4, remaining: 0 },
    time: '2:00 PM',
    relatedTopics: ['leisure', 'interest'],
    restaurant: {
      name: '동명 브런치',
      address: '광주 동구 동명동 155-7',
      distance: '조선대 정문에서 도보 8분',
      category: '브런치',
      mapUrl: 'https://map.kakao.com/link/search/동명+브런치+광주',
      caution: '노쇼 시 환불 불가',
    },
    tags: ['예술', '카페탐방'],
    accentColor: '#5D4037',
    bgColor: '#EFEBE9',
  },
];

export const statusLabel = {
  recruiting: '모집중',
  closing:    '마감임박',
  matched:    '마감',
};
